# Generated by Django 3.0 on 2020-05-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
